# Generated by Codex for the phase 1 MVP schema.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InspectionSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_date", models.DateField(unique=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("job_type", models.CharField(choices=[("master_update", "Master update"), ("plans_import", "Plans import"), ("inspection_sheet_issue", "Inspection sheet issue"), ("daily_report_generate", "Daily report generate")], max_length=64)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="queued", max_length=16)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("machine_no", models.CharField(max_length=64, unique=True)),
                ("machine_name", models.CharField(max_length=255)),
                ("shape_type", models.CharField(choices=[("circle", "Circle"), ("ellipse", "Ellipse"), ("rectangle", "Rectangle")], max_length=16)),
                ("map_x", models.FloatField()),
                ("map_y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("node_type", models.CharField(blank=True, max_length=64)),
                ("department", models.CharField(blank=True, max_length=128)),
                ("category", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"indexes": [models.Index(fields=["code"], name="quality_mas_code_f7d601_idx")]},
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_code", models.CharField(db_index=True, max_length=32)),
                ("parent_code", models.CharField(db_index=True, max_length=32)),
                ("child_code", models.CharField(db_index=True, max_length=32)),
                ("level", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("parent_code", "child_code"), name="unique_structure_parent_child")]},
        ),
        migrations.CreateModel(
            name="InspectionFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.TextField()),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("master", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inspection_files", to="quality.master")),
            ],
            options={"indexes": [models.Index(fields=["file_name"], name="quality_ins_file_na_9c0a4b_idx")]},
        ),
        migrations.CreateModel(
            name="InspectionTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_code", models.CharField(max_length=64)),
                ("normalized_code", models.CharField(max_length=32)),
                ("source_ocr", models.BooleanField(default=False)),
                ("source_excel", models.BooleanField(default=False)),
                ("source_manual", models.BooleanField(default=False)),
                ("requires_inspection_sheet", models.BooleanField(default=False)),
                ("issue_status", models.CharField(choices=[("not_required", "Not required"), ("pending", "Pending"), ("issued", "Issued"), ("missing_file", "Missing file"), ("skipped", "Skipped")], default="not_required", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("master", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inspection_targets", to="quality.master")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="targets", to="quality.inspectionsession")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["session", "normalized_code"], name="quality_ins_session_c4680e_idx"),
                    models.Index(fields=["issue_status"], name="quality_ins_issue_s_17cd16_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("session", "normalized_code"), name="unique_target_per_session_code")],
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("time_slot", models.CharField(choices=[("A", "08:30-10:00"), ("B", "10:10-12:00"), ("C", "12:45-14:45"), ("D", "15:00-17:15")], max_length=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("master", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="histories", to="quality.master")),
            ],
            options={
                "indexes": [models.Index(fields=["date", "time_slot"], name="quality_his_date_bded1a_idx")],
                "constraints": [models.UniqueConstraint(fields=("date", "master", "time_slot"), name="unique_history_date_master_slot")],
            },
        ),
        migrations.CreateModel(
            name="InspectionTargetWarning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("error_code", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="warnings", to="quality.inspectiontarget")),
            ],
        ),
        migrations.CreateModel(
            name="MachineAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="machine_assignments", to="quality.master", to_field="code")),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="quality.machine")),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("machine", "code"), name="unique_machine_assignment")]},
        ),
    ]
