# Generated by Django 5.2.14 on 2026-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_appsetting_master_node_type_1_master_node_type_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='erp_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
