# Generated by Django 5.2.14 on 2026-06-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_classmaster_remove_masterclass_class_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontarget',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
