# Generated by Django 5.2.14 on 2026-06-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_inspectiontarget_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_sheet_issued',
            field=models.BooleanField(default=False),
        ),
    ]
