# Generated by Django 5.2.14 on 2026-06-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_history_is_sheet_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id',
        ),
        migrations.AddField(
            model_name='history',
            name='history_id',
            field=models.BigAutoField(db_column='history_id', primary_key=True, serialize=False),
        ),
    ]
