# Generated by Django 5.2.14 on 2026-06-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_remove_history_id_history_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='history_file_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='history',
            field=models.BooleanField(default=False),
        ),
    ]
