# Generated by Django 5.2.14 on 2026-07-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_machine_machine_class_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inspectiontarget',
            name='unique_target_per_session_code',
        ),
        migrations.RemoveConstraint(
            model_name='masterclass',
            name='unique_master_class',
        ),
        migrations.AddField(
            model_name='inspectiontarget',
            name='class_override',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='inspection_sheet_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='inspectiontarget',
            constraint=models.UniqueConstraint(fields=('session', 'normalized_code', 'class_override'), name='unique_target_per_session_code'),
        ),
        migrations.AddConstraint(
            model_name='masterclass',
            constraint=models.UniqueConstraint(fields=('master', 'class_master'), name='unique_master_class'),
        ),
    ]
