# Generated by Django 5.2.14 on 2026-07-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_seed_class9'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='history',
            name='unique_history_date_master_slot',
        ),
        migrations.AddField(
            model_name='history',
            name='class_override',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('date', 'master', 'time_slot', 'class_override'), name='unique_history_date_master_slot'),
        ),
    ]
