# Generated by Django 5.2.14 on 2026-07-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0015_backfill_history_class_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialInspectionClass9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_sheet_path', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_inspection_class9', to='quality.master')),
            ],
            options={
                'verbose_name': 'Special Inspection Class 9',
                'verbose_name_plural': 'Special Inspection Class 9',
            },
        ),
    ]
