# Generated by Django 5.2.14 on 2026-07-10 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0017_delete_class9_masterclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=64)),
                ('table_name', models.CharField(max_length=128)),
                ('record_id', models.CharField(max_length=128)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('setting_value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectiontarget',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='quality.master'),
        ),
        migrations.AlterField(
            model_name='inspectionfile',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_files', to='quality.master'),
        ),
        migrations.AlterField(
            model_name='inspectiontarget',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_targets', to='quality.master'),
        ),
        migrations.AlterField(
            model_name='inspectiontarget',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='quality.inspectionsession'),
        ),
        migrations.AlterField(
            model_name='inspectiontargetwarning',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings', to='quality.inspectiontarget'),
        ),
        migrations.AlterField(
            model_name='layoutobject',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layout_objects', to='quality.layoutmaster'),
        ),
        migrations.AlterField(
            model_name='layoutobject',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layout_objects', to='quality.machine'),
        ),
        migrations.AlterField(
            model_name='machineassignment',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to='quality.master', to_field='code'),
        ),
        migrations.AlterField(
            model_name='machineassignment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='quality.machine'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_classes', to='quality.master'),
        ),
        migrations.AlterField(
            model_name='specialinspectionclass9',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='special_inspection_class9', to='quality.master'),
        ),
        migrations.AddConstraint(
            model_name='layoutobjecttype',
            constraint=models.CheckConstraint(condition=models.Q(('code__in', ['machine', 'wall', 'path', 'area', 'stairs', 'entrance'])), name='layout_object_type_code_check'),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE quality_machine ADD COLUMN IF NOT EXISTS machine_class smallint NULL;',
            reverse_sql='ALTER TABLE quality_machine DROP COLUMN IF EXISTS machine_class;',
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('machine_class__in', [1, 2, 3, 4, 5, 6, 10]), ('machine_class__isnull', True), _connector='OR'), name='machine_class_check'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('shape_type__in', ['circle', 'ellipse', 'rectangle'])), name='machine_shape_type_check'),
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='settings', serialize=False, to='quality.user')),
                ('theme', models.CharField(default='light', max_length=32)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'worker'])), name='users_role_check'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_system_settings', to='quality.user'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='quality.user'),
        ),
        migrations.AddField(
            model_name='history',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_histories', to='quality.user'),
        ),
        migrations.AddField(
            model_name='history',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_histories', to='quality.user'),
        ),
        migrations.AddField(
            model_name='history',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_histories', to='quality.user'),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_sessions', to='quality.user'),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_inspection_sessions', to='quality.user'),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_inspection_sessions', to='quality.user'),
        ),
        migrations.AddField(
            model_name='inspectionsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_inspection_sessions', to='quality.user'),
        ),
        migrations.AddField(
            model_name='inspectiontarget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_targets', to='quality.user'),
        ),
        migrations.AddField(
            model_name='inspectiontarget',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_inspection_targets', to='quality.user'),
        ),
        migrations.AddField(
            model_name='inspectiontarget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_inspection_targets', to='quality.user'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_jobs', to='quality.user'),
        ),
        migrations.AddField(
            model_name='job',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_jobs', to='quality.user'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_jobs', to='quality.user'),
        ),
        migrations.AddField(
            model_name='layoutmaster',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_layouts', to='quality.user'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['date'], name='quality_his_date_75356e_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['master'], name='quality_his_master__b2567a_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['class_override'], name='quality_his_class_o_ffab8e_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['date', 'class_override'], name='quality_his_date_95a531_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontarget',
            index=models.Index(fields=['normalized_code'], name='quality_ins_normali_b61686_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontarget',
            index=models.Index(fields=['master'], name='quality_ins_master__9a8e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontarget',
            index=models.Index(fields=['session'], name='quality_ins_session_60813e_idx'),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.CheckConstraint(condition=models.Q(('time_slot__in', ['A', 'B', 'C', 'D'])), name='history_time_slot_check'),
        ),
        migrations.AddConstraint(
            model_name='inspectionsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'closed'])), name='inspection_session_status_check'),
        ),
        migrations.AddConstraint(
            model_name='inspectiontarget',
            constraint=models.CheckConstraint(condition=models.Q(('issue_status__in', ['not_required', 'pending', 'issued', 'missing_file', 'skipped'])), name='inspection_target_issue_status_check'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('job_type__in', ['master_update', 'plans_import', 'inspection_sheet_issue', 'daily_report_generate'])), name='job_type_check'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'succeeded', 'failed'])), name='job_status_check'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'logged_at'], name='audit_logs_user_id_3095bc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'record_id'], name='audit_logs_table_n_c2f649_idx'),
        ),
    ]
