# Generated by Django 5.2.14 on 2026-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0018_auditlog_systemsetting_user_history_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='history',
            name='unique_history_date_master_slot',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='browser_settings_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='font_size',
            field=models.FloatField(default=17.33),
        ),
        migrations.AlterField(
            model_name='inspectionsession',
            name='target_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('created_by', 'date', 'master', 'time_slot', 'class_override'), name='unique_history_date_master_slot'),
        ),
        migrations.AddConstraint(
            model_name='inspectionsession',
            constraint=models.UniqueConstraint(fields=('owner_user', 'target_date'), name='unique_inspection_session_owner_date'),
        ),
    ]
