# Generated by Django 5.2.14 on 2026-07-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0019_remove_history_unique_history_date_master_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
