# Generated by Django 5.2.14 on 2026-07-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0020_user_last_login'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='history',
            name='unique_history_date_master_slot',
        ),
        migrations.RemoveConstraint(
            model_name='inspectiontarget',
            name='unique_target_per_session_code',
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('created_by', 'date', 'master', 'time_slot', 'class_override'), name='unique_history_date_master_slot', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='inspectiontarget',
            constraint=models.UniqueConstraint(fields=('session', 'normalized_code', 'class_override'), name='unique_target_per_session_code', nulls_distinct=False),
        ),
    ]
