CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'worker')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id BIGINT PRIMARY KEY,
    theme TEXT NOT NULL DEFAULT 'light',
    CONSTRAINT user_settings_user_id_fk
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT
);

ALTER TABLE quality_inspectionsession
    ADD COLUMN IF NOT EXISTS owner_user_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS created_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS deleted_by_id BIGINT NULL;

ALTER TABLE quality_inspectionsession
    ADD CONSTRAINT inspection_session_owner_user_id_fk
        FOREIGN KEY (owner_user_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT inspection_session_created_by_id_fk
        FOREIGN KEY (created_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT inspection_session_updated_by_id_fk
        FOREIGN KEY (updated_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT inspection_session_deleted_by_id_fk
        FOREIGN KEY (deleted_by_id) REFERENCES users(user_id) ON DELETE RESTRICT;

ALTER TABLE quality_layoutmaster
    ADD COLUMN IF NOT EXISTS owner_user_id BIGINT NULL;

ALTER TABLE quality_layoutmaster
    ADD CONSTRAINT layout_master_owner_user_id_fk
        FOREIGN KEY (owner_user_id) REFERENCES users(user_id) ON DELETE RESTRICT;
