CREATE TABLE IF NOT EXISTS system_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL DEFAULT '',
    updated_by_id BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT system_settings_updated_by_id_fk
        FOREIGN KEY (updated_by_id) REFERENCES users(user_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS audit_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    operation TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL,
    logged_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT audit_logs_user_id_fk
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT
);

ALTER TABLE quality_inspectiontarget
    ADD COLUMN IF NOT EXISTS created_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS deleted_by_id BIGINT NULL;

ALTER TABLE quality_inspectiontarget
    ADD CONSTRAINT inspection_target_created_by_id_fk
        FOREIGN KEY (created_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT inspection_target_updated_by_id_fk
        FOREIGN KEY (updated_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT inspection_target_deleted_by_id_fk
        FOREIGN KEY (deleted_by_id) REFERENCES users(user_id) ON DELETE RESTRICT;

ALTER TABLE quality_history
    ADD COLUMN IF NOT EXISTS created_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS deleted_by_id BIGINT NULL;

ALTER TABLE quality_history
    ADD CONSTRAINT history_created_by_id_fk
        FOREIGN KEY (created_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT history_updated_by_id_fk
        FOREIGN KEY (updated_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT history_deleted_by_id_fk
        FOREIGN KEY (deleted_by_id) REFERENCES users(user_id) ON DELETE RESTRICT;

ALTER TABLE quality_job
    ADD COLUMN IF NOT EXISTS created_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS updated_by_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS deleted_by_id BIGINT NULL;

ALTER TABLE quality_job
    ADD CONSTRAINT quality_job_created_by_id_fk
        FOREIGN KEY (created_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT quality_job_updated_by_id_fk
        FOREIGN KEY (updated_by_id) REFERENCES users(user_id) ON DELETE RESTRICT,
    ADD CONSTRAINT quality_job_deleted_by_id_fk
        FOREIGN KEY (deleted_by_id) REFERENCES users(user_id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS audit_logs_user_logged_at_idx
    ON audit_logs(user_id, logged_at);

CREATE INDEX IF NOT EXISTS audit_logs_table_record_idx
    ON audit_logs(table_name, record_id);
