from django.urls import path

from .views import (
    BulkHideTargetsView,
    BulkHistoryView,
    Class9SettingsView,
    DailyReportGenerateView,
    DailyReportIssueView,
    ErpAutomationView,
    FactoryMapLayoutView,
    FactoryMapLayoutsView,
    FactoryMapView,
    HistoryWriteToFileView,
    InspectionFileOpenByCodeView,
    InspectionFilePdfByCodeView,
    InspectionFilePrintByCodeView,
    InspectionSheetIssueView,
    InspectionTargetDetailView,
    InspectionTargetsView,
    JobDetailView,
    LayoutObjectTypeColorUpdateView,
    MachineListView,
    MachineMasterView,
    ManualTargetsView,
    MasterSearchView,
    MasterUpdateView,
    PlansImportView,
    SeedMasterView,
    SettingsView,
    SingleHistoryView,
    StructureReverseRootsView,
    StructureView,
    TargetInspectionFilePrintView,
    TargetInspectionFileView,
    UploadBackgroundImageView,
)


urlpatterns = [
    path("jobs/<str:job_id>/", JobDetailView.as_view()),
    path("master/update/", MasterUpdateView.as_view()),
    path("master/seed/", SeedMasterView.as_view()),
    path("masters/search/", MasterSearchView.as_view()),
    path("settings/", SettingsView.as_view()),
    path("erp/automate/", ErpAutomationView.as_view()),
    path("plans/import/", PlansImportView.as_view()),
    path("inspection-targets/", InspectionTargetsView.as_view()),
    path("inspection-targets/manual/", ManualTargetsView.as_view()),
    path("inspection-targets/bulk-hide/", BulkHideTargetsView.as_view()),
    path("inspection-targets/<int:target_id>/", InspectionTargetDetailView.as_view()),
    path("inspection-targets/<int:target_id>/file/", TargetInspectionFileView.as_view()),
    path("inspection-targets/<int:target_id>/print-file/", TargetInspectionFilePrintView.as_view()),
    path("history/", SingleHistoryView.as_view()),
    path("history/bulk-upsert/", BulkHistoryView.as_view()),
    path("factory-map/layouts/", FactoryMapLayoutsView.as_view()),
    path("factory-map/layout/", FactoryMapLayoutView.as_view()),
    path("factory-map/layout/<int:layout_id>/", FactoryMapLayoutView.as_view()),
    path("factory-map/upload-image/", UploadBackgroundImageView.as_view()),
    path("factory-map/machines/", MachineListView.as_view()),
    path("machine-master/", MachineMasterView.as_view()),
    path("factory-map/object-type/<str:code>/", LayoutObjectTypeColorUpdateView.as_view()),
    path("factory-map/", FactoryMapView.as_view()),
    path("inspection-sheet/issue/", InspectionSheetIssueView.as_view()),
    path("history/write-to-file/", HistoryWriteToFileView.as_view()),
    path("daily-report/generate/", DailyReportGenerateView.as_view()),
    path("daily-report/issue/", DailyReportIssueView.as_view()),
    path("class9-settings/", Class9SettingsView.as_view()),
    path("class9-settings/<int:pk>/", Class9SettingsView.as_view()),
    path("structure/", StructureView.as_view()),
    path("structure/reverse-roots/", StructureReverseRootsView.as_view()),
    path("inspection-file/open/", InspectionFileOpenByCodeView.as_view()),
    path("inspection-file/pdf/", InspectionFilePdfByCodeView.as_view()),
    path("inspection-file/print/", InspectionFilePrintByCodeView.as_view()),
]
